### ISSUE TITLE
When running pyflowchart, an error is displayed and the flowchart code cannot be found.

### ISSUE THREAD

**Issue by Descarteswyn** [cdfmlr/pyflowchart#12]
__main__.py [-h] [-f FIELD] [-i] [--no-simplify] code_file
__main__.py: error: argument code_file: can't open 'simple.py': [Errno 2] No such file or directory: 'simple.py'

my The PY file name is 'simple.py'
Hope to answer, thank you very much.

**Comment by cdfmlr** [comment]
亲请确定你的 simple.py 位于当前工作目录，或者试试给出文件完整路径名。

CDFMLR

**Comment by Descarteswyn** [comment]
C:\Users\111>python -m pyflowchart simple.py
usage: __main__.py [-h] [-f FIELD] [-i] [--no-simplify] code_file
__main__.py: error: argument code_file: can't open 'simple.py': [Errno 2] No such file or directory: 'simple.py'

you can see it.thanks.

**Comment by cdfmlr** [comment]
> Plz make sure your `simple.py` is under the working path. Or you can also try to offer a full path like `C:\User\111\simple.py`.

May you try this first? 👀

**Comment by Descarteswyn** [comment]
sure，i can understand it.The operation has been completed. Thank you.Thank you for your help. Thank you very much.

**Comment by cdfmlr** [comment]
👌 closed
