### ISSUE TITLE
ConditionNode alignment support

### ISSUE THREAD

**Issue by angerhang** [cdfmlr/pyflowchart#14]
Thank you a lot for the package. It is really useful for one of my use cases in work :D 

As raised in this issue, https://github.com/adrai/flowchart.js/issues/221, it would be great to allow the align-text option set for the condition node. It should be something easy to do to set a positional argument in the constructor for the `ConditionNode(name, isAlign=True)`.

Can this be added quickly? If not, we can maybe do a PR if you point out the caveats :D 

Thought it we need to modify these two definitions?
https://github.com/cdfmlr/pyflowchart/blob/e6694726f2522a0904dc1562563563aba7bf9d88/pyflowchart/node.py#L286 https://github.com/cdfmlr/pyflowchart/blob/e6694726f2522a0904dc1562563563aba7bf9d88/pyflowchart/node.py#L37

**Comment by cdfmlr** [comment]
A great feature. 

However I am in my vacation now. So I can not work on it until this weekend. If you need it urgently, please feel free to make a PR.

**Comment by angerhang** [comment]
Thanks for the quick reply :D 

It is not that urgent haha you probably can do it much faster than me. I will try take a look in the next days. If I don't mange, then it would be great if you can add this in.

Enjoy your holidays! @cdfmlr

**Comment by cdfmlr** [comment]
@angerhang I guess I have made it in https://github.com/cdfmlr/pyflowchart/commit/35487f9e458a673354386b795384d577f33f4e30, basically. You can check to try it now. But I'll merge and release it later, after further tests.

**Comment by cdfmlr** [comment]
I believe this feature is fully supported in the latest [v0.2.3 release](https://github.com/cdfmlr/pyflowchart/releases/tag/v0.2.3r).

You can upgrade and use it. See README or release notes for docs.

```sh
pip install pyflowchart==0.2.3
```

Reopen this issue if there are any related problems.

**Comment by angerhang** [comment]
Thank you so much!
