### ISSUE TITLE
How to save the svg?

### ISSUE THREAD

**Issue by glitchyordis** [cdfmlr/pyflowchart#19]
Hi, the documentation mentions:
"Then you can visit http://flowchart.js.org/ and translate the generated textual representation into SVG flow chart diagrams"

But how do I download the SVG generated at http://flowchart.js.org/?

**Comment by cdfmlr** [comment]
I suggest you can open the developer tools (see https://developer.chrome.com/docs/devtools/open/ for help), go Elements tab and copy the svg source code

```html
<svg>...</svg>
```

from

```
#demo1 > table > tbody > tr > td.diagram.diagram1 > svg
```

and paste it into a `.svg` file.
