### ISSUE TITLE
大佬可以增加一下对于类中的方法的流程解析嘛

### ISSUE THREAD

**Issue by xxcdd** [cdfmlr/pyflowchart#2]

**Comment by cdfmlr** [comment]
我自己在使用的过程中也遇到了类似的问题，我的考虑是提供一种“流程图入口点”的指定。例如：

```python
# example.py

def foo():
    pass

def bar():
    pass

class Fuzz(object):
    def __init__(self):
        pass
    
    def buzz(self):
        pass
    
if __name__ == "__main__":
    pass
```

在运行 pyflowchart 时，提供指定流程图起点的功能。比如，通过一个 `-f` 来指定画代码中哪个方法的流程图：

```sh
$ python3 -m pyflowchart example.py -f bar
$ python3 -m pyflowchart example.py -f Fuzz.buzz
$ python3 -m pyflowchart example.py --main
```

作为一种特殊情况，允许解析 `if __name__ == "__main__":` 下的代码。

---

@xxcdd  你需要的是这样的功能吗？

**Comment by xxcdd** [comment]
是的，这样最好了，还有个需求是可以输出个流程图的html文件不，坐等大佬的更新

**Comment by cdfmlr** [comment]
可以考虑，不过我最近比较忙，预计下个月才能开始这些改进。

作为临时代替，你可以先手动剥离出需要画流程图的方法，单独放入一个文件中调用 pyflowchart。

**Comment by cdfmlr** [comment]
这个在新发布的 v0.1.0 版本中已经支持了🎉，更新之后就可以指定类中方法的流程解析。

```sh
$ pip3 install -U pyflowchart
```

具体用法请参考 [README](https://github.com/cdfmlr/pyflowchart#advanced-usages)。

感谢您提出的建议，也欢迎继续支持本项目。🙏
