### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by jderekito** [cdfmlr/pyflowchart#22]
Hello, 
When I put a single line in http://flowchart.js.org/ such as:
_`sub1=>subroutine: My Subroutine`_
I get error of "Cannot read properties of null."

**Comment by cdfmlr** [comment]
You're right, you can't generate a flowchart with only a single node. To create a flowchart, you need at least two nodes. Here's an example:

```
sub1=>subroutine: My Subroutine
another=>subroutine: Another node

sub1->another
```

**Comment by jderekito** [comment]
Thanks, I was not aware of that.
Cheers, 
Derek
