### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Ms-Amanda** [cdfmlr/pyflowchart#26]
执行时直接报错，不确定是哪里的环境兼容性问题。
如果需要了解更多详细的信息，可以留言问我。谢谢～！
芯片：Apple M1 Pro
OS：13.4 (22F66)
python 环境：系统自带的 python3.8.2

<img width="1511" alt="截屏2023-08-26 17 06 40" src="https://github.com/cdfmlr/pyflowchart/assets/58933397/37877c16-a43f-4c7b-814e-b71a5fb3daab">

**Comment by cdfmlr** [comment]
It's the same as the problem in [this project](https://github.com/tiangolo/typer/issues/371). Will fix it later.

**Comment by cdfmlr** [comment]
该问题（大概）已在最新版本（[v0.3.1](https://github.com/cdfmlr/pyflowchart/releases/tag/v0.3.1)）中修复。新版本已发布到至 [PyPI](https://pypi.org/project/pyflowchart/)，`pip install pyflowchart==0.3.1` 更新即可。

**Comment by Ms-Amanda** [comment]
经测试，已经可以使用了，谢谢
